name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PNPM_HOME: /home/runner/.local/share/pnpm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install pnpm
        run: npm install -g pnpm@11.5.1
      - run: pnpm install --frozen-lockfile --reporter=default
      - name: Test
        run: pnpm turbo  test
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
